---
- hosts: webservers
  remote_user: jenkins
  tasks:
  - name: Fetch App config files...
    shell: cd /AppConfig && git fetch && git merge origin/master
 
    
  - name: Stop Cloud Security Service Containers...
    shell: docker stop cloud.security.service

  - name: Copy Cloud security server war....
    copy: src=cloud-security-server.war dest=/tmp

  - name: Copy war to docker containers...
    shell: docker cp /tmp/cloud-security-server.war cloud.security.service:usr/local/tomcat/webapps 

  - name: Start CS Security Server containers...
    shell: docker start cloud.security.service
